### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by infamedavid** [soulbridge/BBModules#5]
hello, I just purchase your modules and it can't be opened, I m in ubuntu 18 04

this is the log info:
 
`
[0.193 warn src/plugin.cpp:90] Failed to load library /home/david/.Rack/plugins/BBModules/plugin.so: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/david/.Rack/plugins/BBModules/plugin.so)`

[Andrew wrote this in the forum ](https://community.vcvrack.com/t/alright-devices-linux-build-has-library-issues/2837) 

> No compile flags exist to use a different glibc version. Plugins need to be compiled with Ubuntu 16 (or anything with glibc 2.23). 

perhaps can help

thanks!

**Comment by robertocolabene** [comment]
thank you, I will solve it asap!

**Comment by robertocolabene** [comment]
I've sent you an email let me know if it works now.

**Comment by infamedavid** [comment]
fixed!
